### ISSUE TITLE
`variables: require(...)` doesn't work after 1.2.2 -> 2.2.0 upgrade

### ISSUE THREAD

**Issue by pjg** [jonathantneal/postcss-advanced-variables#41]
webpack 3.10
vue 2.5.13

.postcssrc.js:

```
module.exports = {
  "plugins": {
    ...
    "postcss-advanced-variables": {
      variables: require('./src/assets/stylesheets/variables.json')
    },
```

Produces:

```
  name: 'CssSyntaxError',
  reason: 'Could not resolve the variable "$gray-bg" within "$gray-bg"',
```

**Comment by pjg** [comment]
Changing it to:

```
    "postcss-advanced-variables": {
      importPaths: ['./src/assets/stylesheets/variables.json']
    },
```

doesn't help.

**Comment by jonathantneal** [comment]
@pjg, could you give a sample of what your `variables.json` file looks like? Otherwise, I may have a lot of trouble debugging this.

I am already testing for this kind of variables support here: https://github.com/jonathantneal/postcss-advanced-variables/blob/master/.tape.js#L6-L13 which defines `$default` as `custom-fn-value`.

That test then uses this file: https://github.com/jonathantneal/postcss-advanced-variables/blob/master/test/default.css#L4

Which produces this correct result: https://github.com/jonathantneal/postcss-advanced-variables/blob/master/test/default.var-func.expect.css#L2

**Comment by pjg** [comment]
My `variables.json` file looks like this:

```json
{
  "primary-border-radius": "3px",

  "blue": "#2ABCDC",
  "green": "#53D6AE",
  "red": "#E8562A",
  ...
}
```

**Comment by jonathantneal** [comment]
@pjg, does it have a `gray-bg` key? As in, `"gray-bg": "YOUR_HEX_VALUE"`? The error says that variable could not be resolved:

```
Could not resolve the variable "$gray-bg" within "$gray-bg"
```

**Comment by pjg** [comment]
Yeay, it has it:

````
"gray-bg": "#F2F7FA",
```

**Comment by jonathantneal** [comment]
Here’s what I’ve done. I setup a test like this:

https://github.com/jonathantneal/postcss-tests/blob/master/postcss-advanced-variables-test-00/test.js#L15-L17

```js
postcssVariables({
  variables: require('./variables.json')
})
```

Where `variables.json` is:

https://github.com/jonathantneal/postcss-tests/blob/master/postcss-advanced-variables-test-00/variables.json

```json
{
  "primary-border-radius": "3px",
  "blue": "#2ABCDC",
  "green": "#53D6AE",
  "red": "#E8562A",
  "gray-bg": "#F2F7FA"
}
```

And then I’ve tested it against this css file:

https://github.com/jonathantneal/postcss-tests/blob/master/postcss-advanced-variables-test-00/test.css#L2

```css
.test {
  color: $gray-bg;
}
```

And the result is successfully:

https://github.com/jonathantneal/postcss-tests/blob/master/postcss-advanced-variables-test-00/test.expect.css#L2

```css
.test {
  color: #F2F7FA;
}
```

Because this test is passing, I’m not sure where your issue is coming from. Have you tried to log the require statement to see if it is taking in the right variables?

```
console.log(require('./src/assets/stylesheets/variables.json'))
```

The next step would be to get a reduced snippet of your CSS that will cause the error.

**Comment by pjg** [comment]
I guess the issue is with running it through webpack in Vue. I'll experiment with different importing options.

**Comment by pjg** [comment]
Figured it out.

Turns out, now advanced-variables is more restrictive towards invalid variables being used in CSS files. I had a couple of incorrect references and an `@import url("http://...")` statement which didn't work after upgrading to 2.2. I've corrected all of them and things work again. Closing.

Thanks for your support!
